#ifndef _AGARIO_DEFS_H
#define _AGARIO_DEFS_H

#define SNAPSHOTS_DELAY 300
#define INITIAL_PLAYERS_SIZE 20
#define INITIAL_PICKABLES_COUNT 20
#define INITIAL_PICKABLES_SIZE 5
/* packet commands */
#define C_PLAYER_CONNECTED 0
#define C_PLAYER_INIT_OWN 1
#define C_INITIAL_PICKABLES 2
#define C_SPAWN_PICKABLES 3
#define C_PLAYERS_SNAPSHOT 4

#endif //!_AGARIO_DEFS_H